project_id = "emytpfbqfvuzlbuysebw"

[functions.transactions-api]
verify_jwt = false

[functions.recurring-api]
verify_jwt = false

[functions.backup-api]
verify_jwt = false

[functions.financial-stats-api]
verify_jwt = false
